//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.ARDVARCExp
{
    [Serializable]
    public class TestMsg : Message
    {
        public const string k_RosMessageName = "ARDVARC_exp/Test";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.Vector3Msg pos;

        public TestMsg()
        {
            this.pos = new Geometry.Vector3Msg();
        }

        public TestMsg(Geometry.Vector3Msg pos)
        {
            this.pos = pos;
        }

        public static TestMsg Deserialize(MessageDeserializer deserializer) => new TestMsg(deserializer);

        private TestMsg(MessageDeserializer deserializer)
        {
            this.pos = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
        }

        public override string ToString()
        {
            return "TestMsg: " +
            "\npos: " + pos.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
