// Generated by gencpp from file ardvarc/Point.msg
// DO NOT EDIT!


#ifndef ARDVARC_MESSAGE_POINT_H
#define ARDVARC_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardvarc
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : point()  {
      point.assign(0.0);
  }
  Point_(const ContainerAllocator& _alloc)
    : point()  {
  (void)_alloc;
      point.assign(0.0);
  }



   typedef boost::array<double, 3>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::ardvarc::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardvarc::Point_<ContainerAllocator> const> ConstPtr;

}; // struct Point_

typedef ::ardvarc::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::ardvarc::Point > PointPtr;
typedef boost::shared_ptr< ::ardvarc::Point const> PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardvarc::Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardvarc::Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ardvarc::Point_<ContainerAllocator1> & lhs, const ::ardvarc::Point_<ContainerAllocator2> & rhs)
{
  return lhs.point == rhs.point;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ardvarc::Point_<ContainerAllocator1> & lhs, const ::ardvarc::Point_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ardvarc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ardvarc::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardvarc::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardvarc::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardvarc::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardvarc::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardvarc::Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardvarc::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae8631aacd2cccf734667ec88ccd12e3";
  }

  static const char* value(const ::ardvarc::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae8631aacd2cccf7ULL;
  static const uint64_t static_value2 = 0x34667ec88ccd12e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardvarc::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardvarc/Point";
  }

  static const char* value(const ::ardvarc::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardvarc::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] point\n"
;
  }

  static const char* value(const ::ardvarc::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardvarc::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardvarc::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardvarc::Point_<ContainerAllocator>& v)
  {
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDVARC_MESSAGE_POINT_H
