// Generated by gencpp from file ardvarc/TestArrayMsg.msg
// DO NOT EDIT!


#ifndef ARDVARC_MESSAGE_TESTARRAYMSG_H
#define ARDVARC_MESSAGE_TESTARRAYMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardvarc
{
template <class ContainerAllocator>
struct TestArrayMsg_
{
  typedef TestArrayMsg_<ContainerAllocator> Type;

  TestArrayMsg_()
    : vec_tor()  {
      vec_tor.assign(0.0);
  }
  TestArrayMsg_(const ContainerAllocator& _alloc)
    : vec_tor()  {
  (void)_alloc;
      vec_tor.assign(0.0);
  }



   typedef boost::array<double, 3>  _vec_tor_type;
  _vec_tor_type vec_tor;





  typedef boost::shared_ptr< ::ardvarc::TestArrayMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardvarc::TestArrayMsg_<ContainerAllocator> const> ConstPtr;

}; // struct TestArrayMsg_

typedef ::ardvarc::TestArrayMsg_<std::allocator<void> > TestArrayMsg;

typedef boost::shared_ptr< ::ardvarc::TestArrayMsg > TestArrayMsgPtr;
typedef boost::shared_ptr< ::ardvarc::TestArrayMsg const> TestArrayMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardvarc::TestArrayMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardvarc::TestArrayMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ardvarc::TestArrayMsg_<ContainerAllocator1> & lhs, const ::ardvarc::TestArrayMsg_<ContainerAllocator2> & rhs)
{
  return lhs.vec_tor == rhs.vec_tor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ardvarc::TestArrayMsg_<ContainerAllocator1> & lhs, const ::ardvarc::TestArrayMsg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ardvarc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ardvarc::TestArrayMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardvarc::TestArrayMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardvarc::TestArrayMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardvarc::TestArrayMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardvarc::TestArrayMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardvarc::TestArrayMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardvarc::TestArrayMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55258a902e4354bc8b9acf583482a489";
  }

  static const char* value(const ::ardvarc::TestArrayMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55258a902e4354bcULL;
  static const uint64_t static_value2 = 0x8b9acf583482a489ULL;
};

template<class ContainerAllocator>
struct DataType< ::ardvarc::TestArrayMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardvarc/TestArrayMsg";
  }

  static const char* value(const ::ardvarc::TestArrayMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardvarc::TestArrayMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] vec_tor\n"
;
  }

  static const char* value(const ::ardvarc::TestArrayMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardvarc::TestArrayMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vec_tor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TestArrayMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardvarc::TestArrayMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardvarc::TestArrayMsg_<ContainerAllocator>& v)
  {
    s << indent << "vec_tor[]" << std::endl;
    for (size_t i = 0; i < v.vec_tor.size(); ++i)
    {
      s << indent << "  vec_tor[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vec_tor[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDVARC_MESSAGE_TESTARRAYMSG_H
