// Generated by gencpp from file ardvarc/Vector.msg
// DO NOT EDIT!


#ifndef ARDVARC_MESSAGE_VECTOR_H
#define ARDVARC_MESSAGE_VECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ardvarc
{
template <class ContainerAllocator>
struct Vector_
{
  typedef Vector_<ContainerAllocator> Type;

  Vector_()
    : vector()  {
      vector.assign(0.0);
  }
  Vector_(const ContainerAllocator& _alloc)
    : vector()  {
  (void)_alloc;
      vector.assign(0.0);
  }



   typedef boost::array<double, 3>  _vector_type;
  _vector_type vector;





  typedef boost::shared_ptr< ::ardvarc::Vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ardvarc::Vector_<ContainerAllocator> const> ConstPtr;

}; // struct Vector_

typedef ::ardvarc::Vector_<std::allocator<void> > Vector;

typedef boost::shared_ptr< ::ardvarc::Vector > VectorPtr;
typedef boost::shared_ptr< ::ardvarc::Vector const> VectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ardvarc::Vector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ardvarc::Vector_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ardvarc::Vector_<ContainerAllocator1> & lhs, const ::ardvarc::Vector_<ContainerAllocator2> & rhs)
{
  return lhs.vector == rhs.vector;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ardvarc::Vector_<ContainerAllocator1> & lhs, const ::ardvarc::Vector_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ardvarc

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ardvarc::Vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ardvarc::Vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardvarc::Vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ardvarc::Vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardvarc::Vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ardvarc::Vector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ardvarc::Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f869185688f28d6441bbfdc5c564a7c";
  }

  static const char* value(const ::ardvarc::Vector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f869185688f28d6ULL;
  static const uint64_t static_value2 = 0x441bbfdc5c564a7cULL;
};

template<class ContainerAllocator>
struct DataType< ::ardvarc::Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ardvarc/Vector";
  }

  static const char* value(const ::ardvarc::Vector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ardvarc::Vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] vector\n"
;
  }

  static const char* value(const ::ardvarc::Vector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ardvarc::Vector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vector);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Vector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ardvarc::Vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ardvarc::Vector_<ContainerAllocator>& v)
  {
    s << indent << "vector[]" << std::endl;
    for (size_t i = 0; i < v.vector.size(); ++i)
    {
      s << indent << "  vector[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.vector[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDVARC_MESSAGE_VECTOR_H
