//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosArdvarcUnitySim
{
    [Serializable]
    public class RGV_StateMsg : Message
    {
        public const string k_RosMessageName = "ros_ardvarc_unity_sim/RGV_State";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.PointMsg pos;
        public Geometry.QuaternionMsg orientation;
        public bool moving;

        public RGV_StateMsg()
        {
            this.pos = new Geometry.PointMsg();
            this.orientation = new Geometry.QuaternionMsg();
            this.moving = false;
        }

        public RGV_StateMsg(Geometry.PointMsg pos, Geometry.QuaternionMsg orientation, bool moving)
        {
            this.pos = pos;
            this.orientation = orientation;
            this.moving = moving;
        }

        public static RGV_StateMsg Deserialize(MessageDeserializer deserializer) => new RGV_StateMsg(deserializer);

        private RGV_StateMsg(MessageDeserializer deserializer)
        {
            this.pos = Geometry.PointMsg.Deserialize(deserializer);
            this.orientation = Geometry.QuaternionMsg.Deserialize(deserializer);
            deserializer.Read(out this.moving);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.pos);
            serializer.Write(this.orientation);
            serializer.Write(this.moving);
        }

        public override string ToString()
        {
            return "RGV_StateMsg: " +
            "\npos: " + pos.ToString() +
            "\norientation: " + orientation.ToString() +
            "\nmoving: " + moving.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
