
classdef Eulers < ros.Message
    %Eulers MATLAB implementation of ardvarc/Eulers
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ardvarc/Eulers' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ed8507d0eb35eb5807ddbfdda3a6a8c9' % The MD5 Checksum of the message definition
        PropertyList = { 'Eulers_' } % List of non-constant message properties
        ROSPropertyList = { 'eulers' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Eulers_
    end
    methods
        function set.Eulers_(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'Eulers', 'Eulers_');
            obj.Eulers_ = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ardvarc.Eulers.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ardvarc.Eulers(strObj);
        end
    end
end
