
classdef FlightPlan < ros.Message
    %FlightPlan MATLAB implementation of ardvarc/FlightPlan
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ardvarc/FlightPlan' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '53e79edf12cdb10646bd517040409417' % The MD5 Checksum of the message definition
        PropertyList = { 'GoToCenter' 'LookAt' 'OrbitRadius' } % List of non-constant message properties
        ROSPropertyList = { 'go_to_center' 'look_at' 'orbit_radius' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.ardvarc.Point' ...
            'ros.msggen.ardvarc.Point' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        GoToCenter
        LookAt
        OrbitRadius
    end
    methods
        function set.GoToCenter(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.ardvarc.Point'};
            validateattributes(val, validClasses, validAttributes, 'FlightPlan', 'GoToCenter')
            obj.GoToCenter = val;
        end
        function set.LookAt(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.ardvarc.Point'};
            validateattributes(val, validClasses, validAttributes, 'FlightPlan', 'LookAt')
            obj.LookAt = val;
        end
        function set.OrbitRadius(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'FlightPlan', 'OrbitRadius');
            obj.OrbitRadius = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ardvarc.FlightPlan.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ardvarc.FlightPlan(strObj);
        end
    end
end
