
classdef Pose < ros.Message
    %Pose MATLAB implementation of ardvarc/Pose
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ardvarc/Pose' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'cf4913fce816b849e78a417b64f894c3' % The MD5 Checksum of the message definition
        PropertyList = { 'Position' 'Eulers' } % List of non-constant message properties
        ROSPropertyList = { 'position' 'eulers' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.ardvarc.Point' ...
            'ros.msggen.ardvarc.Eulers' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Position
        Eulers
    end
    methods
        function set.Position(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.ardvarc.Point'};
            validateattributes(val, validClasses, validAttributes, 'Pose', 'Position')
            obj.Position = val;
        end
        function set.Eulers(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.ardvarc.Eulers'};
            validateattributes(val, validClasses, validAttributes, 'Pose', 'Eulers')
            obj.Eulers = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ardvarc.Pose.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ardvarc.Pose(strObj);
        end
    end
end
