
classdef Point < ros.Message
    %Point MATLAB implementation of ardvarc/Point
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ardvarc/Point' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'ae8631aacd2cccf734667ec88ccd12e3' % The MD5 Checksum of the message definition
        PropertyList = { 'Point_' } % List of non-constant message properties
        ROSPropertyList = { 'point' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Point_
    end
    methods
        function set.Point_(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'Point', 'Point_');
            obj.Point_ = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ardvarc.Point.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ardvarc.Point(strObj);
        end
    end
end
