
classdef Vector < ros.Message
    %Vector MATLAB implementation of ardvarc/Vector
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'ardvarc/Vector' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '2f869185688f28d6441bbfdc5c564a7c' % The MD5 Checksum of the message definition
        PropertyList = { 'Vector_' } % List of non-constant message properties
        ROSPropertyList = { 'vector' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Vector_
    end
    methods
        function set.Vector_(obj, val)
            validClasses = {'numeric'};
            val = val(:);
            validAttributes = {'vector', 'numel', 3};
            validateattributes(val, validClasses, validAttributes, 'Vector', 'Vector_');
            obj.Vector_ = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.ardvarc.Vector.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.ardvarc.Vector(strObj);
        end
    end
end
