//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Assets
{
    [Serializable]
    public class DumbMsgMsg : Message
    {
        public const string k_RosMessageName = "Assets/DumbMsg";
        public override string RosMessageName => k_RosMessageName;

        public int x;
        public int y;

        public DumbMsgMsg()
        {
            this.x = 0;
            this.y = 0;
        }

        public DumbMsgMsg(int x, int y)
        {
            this.x = x;
            this.y = y;
        }

        public static DumbMsgMsg Deserialize(MessageDeserializer deserializer) => new DumbMsgMsg(deserializer);

        private DumbMsgMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.x);
            deserializer.Read(out this.y);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.x);
            serializer.Write(this.y);
        }

        public override string ToString()
        {
            return "DumbMsgMsg: " +
            "\nx: " + x.ToString() +
            "\ny: " + y.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
